spring:
  profiles:
    default: local
    group:
      local: local, dev
      docker: docker, dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${env.mysql.host}:${env.mysql.port}/${env.mysql.db}

logging:
  level:
    root: INFO
    com.micro: DEBUG
    com.playground: DEBUG

---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 7003


---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080