version: "3.8"

services:
  product-composite:
    build: product-composite
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 150m

  product:
    build: product
    deploy:
      resources:
        limits:
          memory: 150m

  recommendation:
    build: recommendation
    deploy:
      resources:
        limits:
          memory: 150m

  review:
    build: review
    deploy:
      resources:
        limits:
          memory: 150m

  mongodb:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"
    container_name: mongo
    env_file:
      - .env