version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017"

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - .env

  discovery:
    build: discovery
    ports:
      - "${DISCOVERY_PORT}:8761"
    volumes:
      - ./discovery/build/libs/discovery-1.0.jar:/build/app.jar

  product-composite:
    build: product-composite
    ports:
      - "8080:8080"
    volumes:
      - ./product-composite/build/libs/product-composite-1.0.jar:/build/app.jar
    deploy:
      resources:
        limits:
          memory: 180m

  product:
    build: product
    volumes:
      - ./product/build/libs/product-1.0.jar:/build/app.jar
    deploy:
      resources:
        limits:
          memory: 180m
    depends_on:
      - mongodb
      - discovery

  recommendation:
    build: recommendation
    volumes:
      - ./recommendation/build/libs/recommendation-1.0.jar:/build/app.jar
    deploy:
      resources:
        limits:
          memory: 180m
    depends_on:
      - mongodb
      - discovery

  review:
    build: review
    volumes:
      - ./review/build/libs/review-1.0.jar:/build/app.jar
    deploy:
      resources:
        limits:
          memory: 180m
    depends_on:
      - mysql
      - discovery
    restart: on-failure