version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017"

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - .env


  product-composite:
    build: product-composite
    ports:
      - "8080:8080"
    volumes:
      - ./product-composite/build/libs/product-composite-1.0.jar:/build/app.jar
    deploy:
      resources:
        limits:
          memory: 150m

  product:
    build: product
    volumes:
      - ./product/build/libs/product-1.0.jar:/build/app.jar
    deploy:
      resources:
        limits:
          memory: 150m
    depends_on:
      - mongodb

  recommendation:
    build: recommendation
    volumes:
      - ./recommendation/build/libs/recommendation-1.0.jar:/build/app.jar
    deploy:
      resources:
        limits:
          memory: 150m
    depends_on:
      - mongodb

  review:
    build: review
    volumes:
      - ./review/build/libs/review-1.0.jar:/build/app.jar
    deploy:
      resources:
        limits:
          memory: 150m
    depends_on:
      - mysql
    image: mongo:latest
    restart: on-failure