spring:
  profiles:
    default: local, env
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://${env.mongo.host}:${env.mongo.port}
      database: ${env.mongo.db}

logging:
  level:
    root: INFO
    com.micro: DEBUG
    com.playground: DEBUG

---
spring:
  config:
    activate:
      on-profile: local
  mongodb:
    embedded:
      version: 3.0.0
  jpa:
    show-sql: true
server:
  port: 7001


---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080