spring:
  profiles:
    default: local

logging:
  level:
    root: INFO
    com.micro: DEBUG
    com.playground: DEBUG


---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 7001


---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080