# 현 구성은 후에 Service Discovery 로 대체되어진다.
server:
  port: 8080
spring:
  profiles:
    default: local
    group:
      local: local, dev
  application:
    name: product-composite

api:
  common:
    version: 1.0
    title: MSA playground API document
    description: this document for retrieve API information
  product-composite:
    get-composite-product:
      description: Returns a composite view of the specified product id

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: ${env.eureka.protocol}://${env.eureka.host}:${env.eureka.port}/eureka

---
spring:
  config:
    activate:
      on-profile: local

app:
  product:
    host: localhost
    port: 7001
  recommendation:
    host: localhost
    port: 7002
  review:
    host: localhost
    port: 7003

---
spring:
  config:
    activate:
      on-profile: docker
app:
  product:
    host: product
    port: 8080
  recommendation:
    host: recommendation
    port: 8080
  review:
    host: review
    port: 8080

